server:
  port: 8050

spring:  application:    name: zuul

eureka:  client:
    service-url:      defaultZone: http://user:password123@localhost:8761/eureka
      
logging:  level:    root: INFO
    
zuul:
  ignoredServices: '*'
  routes:
    app-provider-user:
      path: /user/**
      serviceId: provider-user
    app-sidecar:
      path: /sidecar/**
      serviceId: sidecar